[package]
name = "garment-derive"
description = "A library for diagnostics"
license = "MIT"
repository = "https://github.com/anonrig/garment"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
