name: Rustup

description: Install Rust with minimal profile and additional components

inputs:
  # See https://rust-lang.github.io/rustup/concepts/components.html
  clippy:
    default: 'false'
    required: false
    description: Clippy is a lint tool that provides extra checks for common mistakes and stylistic choices.
  fmt:
    default: 'false'
    required: false
    description: Rustfmt is a tool for automatically formatting code.
  docs:
    default: 'false'
    required: false
    description: This is a local copy of the Rust documentation. Use the rustup doc command to open the documentation in a web browser.
  restore-cache:
    default: 'true'
    required: false
    description: Use this to restore cache after checkout.
  save-cache:
    default: 'false'
    required: false
    description: Use this to save cache after checkout.
  shared-key:
    default: 'warm'
    required: false
    description: Use this as the shared key for cache.

runs:
  using: composite
  steps:
    - name: Print Inputs
      shell: bash
      run: |
        echo 'clippy: ${{ inputs.clippy }}'
        echo 'fmt: ${{ inputs.fmt }}'
        echo 'docs: ${{ inputs.docs }}'
        echo 'restore-cache: ${{ inputs.restore-cache }}'
        echo 'save-cache: ${{ inputs.save-cache }}'

    - name: Remove `profile` line on MacOS
      shell: bash
      if: runner.os == 'macOS'
      run: sed -i '' '/profile/d' rust-toolchain.toml

    - name: Remove `profile` line on non-MacOS
      shell: bash
      if: runner.os != 'macOS'
      run: sed -i '/profile/d' rust-toolchain.toml

    - name: Set minimal
      shell: bash
      run: rustup set profile minimal

    - name: Add Clippy
      shell: bash
      if: ${{ inputs.clippy == 'true' }}
      run: rustup component add clippy

    - name: Add Rustfmt
      shell: bash
      if: ${{ inputs.fmt == 'true' }}
      run: rustup component add rustfmt

    - name: Add docs
      shell: bash
      if: ${{ inputs.docs == 'true' }}
      run: rustup component add rust-docs

    - name: Install
      shell: bash
      run: |
        rustup show
        git restore .

    - name: Cache on ${{ github.ref_name }}
      uses: Swatinem/rust-cache@v2
      if: ${{ inputs.restore-cache == 'true' }}
      with:
        shared-key: ${{ inputs.shared-key }}
        save-if: ${{ inputs.save-cache == 'true' }}
